#!/bin/bash
# Small settings tweaks for Dapper Linux

# Set Bubblewrap setuid as we do not enable user namespaces
chmod u+s /usr/bin/bwrap

# reload gsettings changes
glib-compile-schemas /usr/share/glib-2.0/schemas 2>/dev/null
dconf update

# polkitd needs to access /proc to function
usermod -aG proc_access polkitd
systemctl restart polkit

# Remove annoying icons
if [ -e /usr/share/applications/dnssec-trigger-panel.desktop ]
then
    sh -c 'echo "NoDisplay=true" >> /usr/share/applications/dnssec-trigger-panel.desktop'
fi
if [ -e /usr/share/applications/lash-panel.desktop ]
then
    sh -c 'echo "NoDisplay=true" >> /usr/share/applications/lash-panel.desktop'
fi
if [ -e /usr/share/applications/chkrootkit.desktop ]
then
    sh -c 'echo "NoDisplay=true" >> /usr/share/applications/chkrootkit.desktop'
fi
java_jconsole=/usr/share/applications/java-1.8.0-openjdk-*-jconsole.desktop
java_policytool=/usr/share/applications/java-1.8.0-openjdk-*-policytool.desktop
if [ -e $java_jconsole ]
then
    rm $java_jconsole &> /dev/null || :
fi
if [ -e $java_policytool ]
then
    rm $java_policytool &> /dev/null || :
fi
if [ -e /usr/share/applications/org.gnome.Calculator.desktop ]
then
    sed -i "s/Categories=GNOME;GTK;Utility;Calculator;/Categories=GNOME;GTK;Utility;Calculator;X-GNOME-Utilities;/g" /usr/share/applications/org.gnome.Calculator.desktop
fi

# Fix Nautilus Icon
if [ -e /usr/share/icons/Numix-Circle/48/apps/file-manager.svg ]
then
    ln -sf /usr/share/icons/Numix-Circle/48/apps/file-manager.svg /usr/share/icons/Numix-Circle/48/apps/org.gnome.Nautilus.svg
fi

# Fix Tilix Icon
if [ -e /usr/share/icons/Numix-Circle/48/apps/terminix.svg ]
then
    ln -sf /usr/share/icons/Numix-Circle/48/apps/terminix.svg /usr/share/icons/Numix-Circle/48/apps/com.gexperts.Tilix.svg
fi

# Enable DNSSEC through NetworkManager
if [ -e /etc/NetworkManager/NetworkManager.conf ]
then
    sh -c 'echo "dns=unbound" >> /etc/NetworkManager/NetworkManager.conf'
fi

# Set Grub to boot the first kernel, not the last saved kernel
if [ -e /etc/default/grub ]
then
    sed -i "s/GRUB_DEFAULT=saved/GRUB_DEFAULT=0/g" /etc/default/grub
fi
