#!/bin/bash

java_jconsole=/usr/share/applications/java-1.8.0-openjdk-*-jconsole.desktop
java_policytool=/usr/share/applications/java-1.8.0-openjdk-*-policytool.desktop
if [ -e $java_jconsole ]
then
    rm $java_jconsole &> /dev/null || :
fi
if [ -e $java_policytool ]
then
    rm $java_policytool &> /dev/null || :
fi
